// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/mbatimel/RegressionAnalysis/internal/models"
	"github.com/mbatimel/RegressionAnalysis/pkg/interfaces"
)

type RegressionMlrRegression func(ctx context.Context, observer string, vars []string, dataPoints []models.DataPoint) (formula string, err error)
type RegressionRidgeRegression func(ctx context.Context, xData [][]float64, yData [][]float64, alpha float64, tol float64, normalize bool) (formula string, err error)
type RegressionLassoRegression func(ctx context.Context, xData [][]float64, yData [][]float64, alpha float64, tol float64, normalize bool) (formula string, err error)
type RegressionElasticNetRegression func(ctx context.Context, params models.ElasticNetParams) (formula map[string][]float64, err error)

type MiddlewareRegression func(next interfaces.Regression) interfaces.Regression

type MiddlewareRegressionMlrRegression func(next RegressionMlrRegression) RegressionMlrRegression
type MiddlewareRegressionRidgeRegression func(next RegressionRidgeRegression) RegressionRidgeRegression
type MiddlewareRegressionLassoRegression func(next RegressionLassoRegression) RegressionLassoRegression
type MiddlewareRegressionElasticNetRegression func(next RegressionElasticNetRegression) RegressionElasticNetRegression
