// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mbatimel/RegressionAnalysis/internal/interfaces"
)

type httpRegression struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverRegression
	base             interfaces.Regression
}

func NewRegression(svcRegression interfaces.Regression) (srv *httpRegression) {

	srv = &httpRegression{
		base: svcRegression,
		svc:  newServerRegression(svcRegression),
	}
	return
}

func (http *httpRegression) Service() *serverRegression {
	return http.svc
}

func (http *httpRegression) WithLog() *httpRegression {
	http.svc.WithLog()
	return http
}

func (http *httpRegression) WithMetrics() *httpRegression {
	http.svc.WithMetrics()
	return http
}

func (http *httpRegression) WithErrorHandler(handler ErrorHandler) *httpRegression {
	http.errorHandler = handler
	return http
}

func (http *httpRegression) SetRoutes(route *fiber.App) {
	route.Get("/api/v1/mlr", http.serveMlrRegression)
	route.Get("/api/v1/ridge", http.serveRidgeRegression)
	route.Get("/api/v1/lasso", http.serveLassoRegression)
	route.Get("/api/v1/elasticNet", http.serveElasticNetRegression)
}
