// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/mbatimel/RegressionAnalysis/internal/models"
	"github.com/mbatimel/RegressionAnalysis/pkg/interfaces"
	"gonum.org/v1/gonum/mat"
)

type serverRegression struct {
	svc                  interfaces.Regression
	mlrRegression        RegressionMlrRegression
	ridgeRegression      RegressionRidgeRegression
	lassoRegression      RegressionLassoRegression
	elasticNetRegression RegressionElasticNetRegression
}

type MiddlewareSetRegression interface {
	Wrap(m MiddlewareRegression)
	WrapMlrRegression(m MiddlewareRegressionMlrRegression)
	WrapRidgeRegression(m MiddlewareRegressionRidgeRegression)
	WrapLassoRegression(m MiddlewareRegressionLassoRegression)
	WrapElasticNetRegression(m MiddlewareRegressionElasticNetRegression)

	WithMetrics()
	WithLog()
}

func newServerRegression(svc interfaces.Regression) *serverRegression {
	return &serverRegression{
		elasticNetRegression: svc.ElasticNetRegression,
		lassoRegression:      svc.LassoRegression,
		mlrRegression:        svc.MlrRegression,
		ridgeRegression:      svc.RidgeRegression,
		svc:                  svc,
	}
}

func (srv *serverRegression) Wrap(m MiddlewareRegression) {
	srv.svc = m(srv.svc)
	srv.mlrRegression = srv.svc.MlrRegression
	srv.ridgeRegression = srv.svc.RidgeRegression
	srv.lassoRegression = srv.svc.LassoRegression
	srv.elasticNetRegression = srv.svc.ElasticNetRegression
}

func (srv *serverRegression) MlrRegression(ctx context.Context, observer string, vars []string, dataPoints []models.DataPoint) (formula string, err error) {
	return srv.mlrRegression(ctx, observer, vars, dataPoints)
}

func (srv *serverRegression) RidgeRegression(ctx context.Context, XData [][]float64, YData [][]float64, alpha float64, tol float64, normalize bool) (formula *mat.Dense, err error) {
	return srv.ridgeRegression(ctx, XData, YData, alpha, tol, normalize)
}

func (srv *serverRegression) LassoRegression(ctx context.Context, XData [][]float64, YData [][]float64, alpha float64, tol float64, normalize bool) (formula *mat.Dense, err error) {
	return srv.lassoRegression(ctx, XData, YData, alpha, tol, normalize)
}

func (srv *serverRegression) ElasticNetRegression(ctx context.Context, params models.ElasticNetParams) (formula map[string][]float64, err error) {
	return srv.elasticNetRegression(ctx, params)
}

func (srv *serverRegression) WrapMlrRegression(m MiddlewareRegressionMlrRegression) {
	srv.mlrRegression = m(srv.mlrRegression)
}

func (srv *serverRegression) WrapRidgeRegression(m MiddlewareRegressionRidgeRegression) {
	srv.ridgeRegression = m(srv.ridgeRegression)
}

func (srv *serverRegression) WrapLassoRegression(m MiddlewareRegressionLassoRegression) {
	srv.lassoRegression = m(srv.lassoRegression)
}

func (srv *serverRegression) WrapElasticNetRegression(m MiddlewareRegressionElasticNetRegression) {
	srv.elasticNetRegression = m(srv.elasticNetRegression)
}

func (srv *serverRegression) WithMetrics() {
	srv.Wrap(metricsMiddlewareRegression)
}

func (srv *serverRegression) WithLog() {
	srv.Wrap(loggerMiddlewareRegression())
}
