// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"github.com/mbatimel/RegressionAnalysis/internal/models"
	"gonum.org/v1/gonum/mat"
)

type requestRegressionMlrRegression struct {
	Observer   string             `json:"observer,omitempty"`
	Vars       []string           `json:"vars,omitempty"`
	DataPoints []models.DataPoint `json:"dataPoints,omitempty"`
}

type responseRegressionMlrRegression struct {
	Formula string `json:"formula,omitempty"`
}

type requestRegressionRidgeRegression struct {
	XData     [][]float64 `json:"XData,omitempty"`
	YData     [][]float64 `json:"YData,omitempty"`
	Alpha     float64     `json:"alpha,omitempty"`
	Tol       float64     `json:"tol,omitempty"`
	Normalize bool        `json:"normalize,omitempty"`
}

type responseRegressionRidgeRegression struct {
	Formula *mat.Dense `json:"formula,omitempty"`
}

type requestRegressionLassoRegression struct {
	XData     [][]float64 `json:"XData,omitempty"`
	YData     [][]float64 `json:"YData,omitempty"`
	Alpha     float64     `json:"alpha,omitempty"`
	Tol       float64     `json:"tol,omitempty"`
	Normalize bool        `json:"normalize,omitempty"`
}

type responseRegressionLassoRegression struct {
	Formula *mat.Dense `json:"formula,omitempty"`
}

type requestRegressionElasticNetRegression struct {
	Params models.ElasticNetParams `json:"params,omitempty"`
}

type responseRegressionElasticNetRegression struct {
	Formula map[string][]float64 `json:"formula,omitempty"`
}
