// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/gofiber/fiber/v2"
	customhandlers "github.com/mbatimel/RegressionAnalysis/internal/transport/jsonRPC/custom-handlers"
)

func (http *httpRegression) mlrRegression(ctx context.Context, request requestRegressionMlrRegression) (response responseRegressionMlrRegression, err error) {

	response.Formula, err = http.svc.MlrRegression(ctx, request.Observer, request.Vars, request.DataPoints)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveMlrRegression(ctx *fiber.Ctx) (err error) {

	var request requestRegressionMlrRegression
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.MlrRegression(ctx, http.svc, request.Observer, request.Vars, request.DataPoints)
}
func (http *httpRegression) mlrRegressionCSV(ctx context.Context, request requestRegressionMlrRegressionCSV) (response responseRegressionMlrRegressionCSV, err error) {

	response.Formula, err = http.svc.MlrRegressionCSV(ctx, request.File)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveMlrRegressionCSV(ctx *fiber.Ctx) (err error) {

	var request requestRegressionMlrRegressionCSV
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.MlrRegressionCSV(ctx, http.svc, request.File)
}
func (http *httpRegression) ridgeRegression(ctx context.Context, request requestRegressionRidgeRegression) (response responseRegressionRidgeRegression, err error) {

	response.Formula, err = http.svc.RidgeRegression(ctx, request.XData, request.YData, request.Alpha, request.Tol, request.Normalize)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveRidgeRegression(ctx *fiber.Ctx) (err error) {

	var request requestRegressionRidgeRegression
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.RidgeRegression(ctx, http.svc, request.XData, request.YData, request.Alpha, request.Tol, request.Normalize)
}
func (http *httpRegression) lassoRegression(ctx context.Context, request requestRegressionLassoRegression) (response responseRegressionLassoRegression, err error) {

	response.Formula, err = http.svc.LassoRegression(ctx, request.XData, request.YData, request.Alpha, request.Tol, request.Normalize)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveLassoRegression(ctx *fiber.Ctx) (err error) {

	var request requestRegressionLassoRegression
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.LassoRegression(ctx, http.svc, request.XData, request.YData, request.Alpha, request.Tol, request.Normalize)
}
func (http *httpRegression) elasticNetRegression(ctx context.Context, request requestRegressionElasticNetRegression) (response responseRegressionElasticNetRegression, err error) {

	response.Formula, err = http.svc.ElasticNetRegression(ctx, request.Params)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveElasticNetRegression(ctx *fiber.Ctx) (err error) {

	var request requestRegressionElasticNetRegression
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.ElasticNetRegression(ctx, http.svc, request.Params)
}
