// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import "github.com/mbatimel/RegressionAnalysis/internal/models"

type requestRegressionMlrRegression struct {
	Observer   string             `json:"observer,omitempty"`
	Vars       []string           `json:"vars,omitempty"`
	DataPoints []models.DataPoint `json:"dataPoints,omitempty"`
}

type responseRegressionMlrRegression struct {
	Formula map[string]interface{} `json:"formula,omitempty"`
}

type requestRegressionMlrRegressionCSV struct {
	File []byte `json:"file,omitempty"`
}

type responseRegressionMlrRegressionCSV struct {
	Formula map[string]interface{} `json:"formula,omitempty"`
}

type requestRegressionMlrRegressionExcel struct {
	File []byte `json:"file,omitempty"`
}

type responseRegressionMlrRegressionExcel struct {
	Formula map[string]interface{} `json:"formula,omitempty"`
}

type requestRegressionOnlyMlrRegression struct {
	Observer   string             `json:"observer,omitempty"`
	Vars       []string           `json:"vars,omitempty"`
	DataPoints []models.DataPoint `json:"dataPoints,omitempty"`
}

type responseRegressionOnlyMlrRegression struct {
	Formula map[string]interface{} `json:"formula,omitempty"`
}

type requestRegressionOnlyMlrRegressionCSV struct {
	File []byte `json:"file,omitempty"`
}

type responseRegressionOnlyMlrRegressionCSV struct {
	Formula map[string]interface{} `json:"formula,omitempty"`
}

type requestRegressionOnlyMlrRegressionExcel struct {
	File []byte `json:"file,omitempty"`
}

type responseRegressionOnlyMlrRegressionExcel struct {
	Formula map[string]interface{} `json:"formula,omitempty"`
}
