// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/mbatimel/RegressionAnalysis/internal/models"
	"github.com/mbatimel/RegressionAnalysis/internal/transport/jsonRPC/externalapi/viewer"
	"github.com/mbatimel/RegressionAnalysis/pkg/interfaces"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"mime/multipart"
	"time"
)

type loggerRegression struct {
	next interfaces.Regression
}

func loggerMiddlewareRegression() MiddlewareRegression {
	return func(next interfaces.Regression) interfaces.Regression {
		return &loggerRegression{next: next}
	}
}

func (m loggerRegression) MlrRegression(ctx context.Context, observer string, vars []string, dataPoints []models.DataPoint) (formula string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Regression").Str("method", "mlrRegression").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "regression.mlrRegression",
				"request": viewer.Sprintf("%+v", requestRegressionMlrRegression{
					DataPoints: dataPoints,
					Observer:   observer,
					Vars:       vars,
				}),
				"response": viewer.Sprintf("%+v", responseRegressionMlrRegression{Formula: formula}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call mlrRegression")
			return
		}
		logger.Info().Func(logHandle).Msg("call mlrRegression")
	}(time.Now())
	return m.next.MlrRegression(ctx, observer, vars, dataPoints)
}

func (m loggerRegression) MlrRegressionCSV(ctx context.Context, observer string, vars []string, file multipart.File) (formula string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Regression").Str("method", "mlrRegressionCSV").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "regression.mlrRegressionCSV",
				"request": viewer.Sprintf("%+v", requestRegressionMlrRegressionCSV{
					File:     file,
					Observer: observer,
					Vars:     vars,
				}),
				"response": viewer.Sprintf("%+v", responseRegressionMlrRegressionCSV{Formula: formula}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call mlrRegressionCSV")
			return
		}
		logger.Info().Func(logHandle).Msg("call mlrRegressionCSV")
	}(time.Now())
	return m.next.MlrRegressionCSV(ctx, observer, vars, file)
}

func (m loggerRegression) RidgeRegression(ctx context.Context, xData [][]float64, yData [][]float64, alpha float64, tol float64, normalize bool) (formula string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Regression").Str("method", "ridgeRegression").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "regression.ridgeRegression",
				"request": viewer.Sprintf("%+v", requestRegressionRidgeRegression{
					Alpha:     alpha,
					Normalize: normalize,
					Tol:       tol,
					XData:     xData,
					YData:     yData,
				}),
				"response": viewer.Sprintf("%+v", responseRegressionRidgeRegression{Formula: formula}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call ridgeRegression")
			return
		}
		logger.Info().Func(logHandle).Msg("call ridgeRegression")
	}(time.Now())
	return m.next.RidgeRegression(ctx, xData, yData, alpha, tol, normalize)
}

func (m loggerRegression) LassoRegression(ctx context.Context, xData [][]float64, yData [][]float64, alpha float64, tol float64, normalize bool) (formula string, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Regression").Str("method", "lassoRegression").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "regression.lassoRegression",
				"request": viewer.Sprintf("%+v", requestRegressionLassoRegression{
					Alpha:     alpha,
					Normalize: normalize,
					Tol:       tol,
					XData:     xData,
					YData:     yData,
				}),
				"response": viewer.Sprintf("%+v", responseRegressionLassoRegression{Formula: formula}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call lassoRegression")
			return
		}
		logger.Info().Func(logHandle).Msg("call lassoRegression")
	}(time.Now())
	return m.next.LassoRegression(ctx, xData, yData, alpha, tol, normalize)
}

func (m loggerRegression) ElasticNetRegression(ctx context.Context, params models.ElasticNetParams) (formula map[string][]float64, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Regression").Str("method", "elasticNetRegression").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "regression.elasticNetRegression",
				"request":  viewer.Sprintf("%+v", requestRegressionElasticNetRegression{Params: params}),
				"response": viewer.Sprintf("%+v", responseRegressionElasticNetRegression{Formula: formula}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call elasticNetRegression")
			return
		}
		logger.Info().Func(logHandle).Msg("call elasticNetRegression")
	}(time.Now())
	return m.next.ElasticNetRegression(ctx, params)
}
