// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/gofiber/fiber/v2"
	customhandlers "github.com/mbatimel/RegressionAnalysis/internal/transport/jsonRPC/custom-handlers"
	"io"
)

func (http *httpRegression) mlrRegression(ctx context.Context, request requestRegressionMlrRegression) (response responseRegressionMlrRegression, err error) {

	response.Formula, err = http.svc.MlrRegression(ctx, request.Observer, request.Vars, request.DataPoints)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveMlrRegression(ctx *fiber.Ctx) (err error) {

	var request requestRegressionMlrRegression
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.MlrRegression(ctx, http.svc, request.Observer, request.Vars, request.DataPoints)
}
func (http *httpRegression) mlrRegressionCSV(ctx context.Context, request requestRegressionMlrRegressionCSV) (response responseRegressionMlrRegressionCSV, err error) {

	response.Formula, err = http.svc.MlrRegressionCSV(ctx, request.File)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpRegression) serveMlrRegressionCSV(ctx *fiber.Ctx) error {
	// кастомная реализация, не убирать и возвращать
	// Получаем файл из формы
	fileHeader, err := ctx.FormFile("file")
	if err != nil {
		ctx.Status(fiber.StatusBadRequest).SendString("failed to get file: " + err.Error())
		return err
	}

	// Открываем файл
	file, err := fileHeader.Open()
	if err != nil {
		ctx.Status(fiber.StatusInternalServerError).SendString("failed to open file: " + err.Error())
		return err
	}
	defer file.Close()

	// Читаем файл в []byte
	fileBytes, err := io.ReadAll(file)
	if err != nil {
		ctx.Status(fiber.StatusInternalServerError).SendString("failed to read file: " + err.Error())
		return err
	}

	// Передаём файл в обработчик
	return customhandlers.MlrRegressionCSV(ctx, http.svc, fileBytes)
}
func (http *httpRegression) serveMlrRegressionExcel(ctx *fiber.Ctx) error {
	// кастомная реализация, не убирать и возвращать
	// Получаем файл из формы
	fileHeader, err := ctx.FormFile("file")
	if err != nil {
		ctx.Status(fiber.StatusBadRequest).SendString("failed to get file: " + err.Error())
		return err
	}

	// Открываем файл
	file, err := fileHeader.Open()
	if err != nil {
		ctx.Status(fiber.StatusInternalServerError).SendString("failed to open file: " + err.Error())
		return err
	}
	defer file.Close()

	// Читаем файл в []byte
	fileBytes, err := io.ReadAll(file)
	if err != nil {
		ctx.Status(fiber.StatusInternalServerError).SendString("failed to read file: " + err.Error())
		return err
	}

	// Передаём файл в обработчик
	return customhandlers.MlrRegressionExcel(ctx, http.svc, fileBytes)
}
