openapi: 3.0.0
info:
    title: Regression API
    version: 0.0.1
servers:
    - {}
paths:
    /api/v1/mlr:
        post:
            tags:
                - Regression
            summary: Ручка по рассчету MLR регрессии
            description: Ручка возвращает формулу и параметры
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/requestRegressionMlrRegression'
            responses:
                "200":
                    description: Successful operation
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "405":
                    description: Method Not Allowed
                "500":
                    description: Internal Server Error
    /api/v1/mlrCSV:
        post:
            tags:
                - Regression
            summary: Ручка по рассчету MLR регрессии из scv
            description: Ручка возвращает формулу и параметры
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/requestRegressionMlrRegressionCSV'
            responses:
                "200":
                    description: Successful operation
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "405":
                    description: Method Not Allowed
                "500":
                    description: Internal Server Error
    /api/v1/mlrExcel:
        post:
            tags:
                - Regression
            summary: Ручка по рассчету MLR регрессии из Execel
            description: Ручка возвращает формулу и параметры
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/requestRegressionMlrRegressionExcel'
            responses:
                "200":
                    description: Successful operation
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "405":
                    description: Method Not Allowed
                "500":
                    description: Internal Server Error
components:
    schemas:
        models.DataPoint:
            type: object
            properties:
                err:
                    type: number
                    format: float
                obs:
                    type: number
                    format: float
                pred:
                    type: number
                    format: float
                vares:
                    type: array
                    items:
                        type: number
                        format: float
                    nullable: true
        requestRegressionMlrRegression:
            type: object
            required:
                - observer
                - vars
                - dataPoints
            properties:
                dataPoints:
                    type: array
                    items:
                        $ref: '#/components/schemas/models.DataPoint'
                    nullable: true
                observer:
                    type: string
                vars:
                    type: array
                    items:
                        type: string
                    nullable: true
            description: Ручка возвращает формулу и параметры
        requestRegressionMlrRegressionCSV:
            type: object
            required:
                - file
            properties:
                file:
                    type: string
                    format: byte
            description: Ручка возвращает формулу и параметры
        requestRegressionMlrRegressionExcel:
            type: object
            required:
                - file
            properties:
                file:
                    type: string
                    format: byte
            description: Ручка возвращает формулу и параметры
        responseRegressionMlrRegression:
            type: object
            required:
                - formula
            properties:
                formula:
                    type: object
                    additionalProperties:
                        type: object
                        nullable: true
            description: Ручка возвращает формулу и параметры
        responseRegressionMlrRegressionCSV:
            type: object
            required:
                - formula
            properties:
                formula:
                    type: object
                    additionalProperties:
                        type: object
                        nullable: true
            description: Ручка возвращает формулу и параметры
        responseRegressionMlrRegressionExcel:
            type: object
            required:
                - formula
            properties:
                formula:
                    type: object
                    additionalProperties:
                        type: object
                        nullable: true
            description: Ручка возвращает формулу и параметры
